import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Navbar/Navbar";

const inter = Inter({
  subsets: ["latin"],
  weight: ["100", "400"],
});

export const metadata = {
  title: "Home | Car doctor",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className}`}>
        <Navbar></Navbar>
        <main className="max-w-7xl border mx-auto">{children}</main>
      </body>
    </html>
  );
}
